version: "3"

services:
    node:
      container_name: carbon.node
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - ./site:/home/node/app
      ports:
        - 3030:3030
